epoch: 30
batch_size: 24
lr: 0.0001
worker: 4

image_size: 256

source_folder: '../human-recovery/datasets/bmvc/bmvc_flowers/train_128/inputs/scribble'
target_folder: '../human-recovery/datasets/bmvc/bmvc_flowers/train_128/gt/'
